/**
 * Employee model
 * --------------------------------------------------------------
 * Fields:
 *   id         - auto-generated by MongoDB (exposed as "id" in JSON)
 *   fullName   - string, required
 *   department - string, required
 *   role       - string, required
 *   salary     - number, required (>= 0)
 *   joinDate   - date, required
 *   createdAt  - timestamp, set automatically
 *   updatedAt  - timestamp, refreshed automatically on every update
 */
const mongoose = require('mongoose');

const employeeSchema = new mongoose.Schema(
  {
    fullName: {
      type: String,
      required: [true, 'Full name is required'],
      trim: true,
      maxlength: [100, 'Full name must be 100 characters or fewer'],
    },
    department: {
      type: String,
      required: [true, 'Department is required'],
      trim: true,
      maxlength: [100, 'Department must be 100 characters or fewer'],
    },
    role: {
      type: String,
      required: [true, 'Role is required'],
      trim: true,
      maxlength: [100, 'Role must be 100 characters or fewer'],
    },
    salary: {
      type: Number,
      required: [true, 'Salary is required'],
      min: [0, 'Salary cannot be negative'],
    },
    joinDate: {
      type: Date,
      required: [true, 'Join date is required'],
    },
  },
  {
    // Adds createdAt and updatedAt automatically
    timestamps: true,
  }
);

/**
 * Duplicate protection: the same person (name) in the same department
 * with the same role cannot be added twice. The collation makes the check
 * case-insensitive, so "Priya Sharma" and "priya sharma" count as duplicates.
 * MongoDB reports a violation as error code 11000, which the server
 * translates into an HTTP 409 response.
 */
employeeSchema.index(
  { fullName: 1, department: 1, role: 1 },
  { unique: true, collation: { locale: 'en', strength: 2 }, name: 'unique_employee' }
);

// Return "id" instead of "_id" / "__v" in every JSON response
employeeSchema.set('toJSON', {
  versionKey: false,
  transform: (_doc, ret) => {
    ret.id = ret._id.toString();
    delete ret._id;
    return ret;
  },
});

module.exports = mongoose.model('Employee', employeeSchema);
